openapi: 3.0.3
info:
  version: 1.0.0
  title: API de Gerenciamento de Usuários e Pratos
  description: Esta é uma API para gerenciar usuários e pratos com autenticação JWT.
servers:
  - url: http://localhost:3000/api
    description: Servidor local

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Link:
      type: object
      properties:
        href:
          type: string
        method:
          type: string
      required: [href]

    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'

    Meta:
      type: object
      properties:
        correlationId:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
          required: [code, message]
        meta:
          $ref: '#/components/schemas/Meta'
      required: [error]
